// Each theme ships with:
//   • CSS vars injected onto <html>
//   • bodyClass applied to <body>
//   • overlayHTML injected into #theme-overlay (absolute, z:0, pointer-events:none)
//   • overlayScript: JS run once after overlay mounts (visual only)
//   • cursorScript: JS for the per-theme custom cursor
//   • typography: per-theme type scale, rhythm, and weight tokens (NEW v4.1)
// ─────────────────────────────────────────────────────────────────────────────

export const THEMES = {

  // ══════════════════════════════════════════════════════════════════════════
  // 1. POOKIE  ·  Pink × Purple Galaxy — Upgraded
  //    Cursor: sparkle dot with trailing aurora stardust
  // ══════════════════════════════════════════════════════════════════════════
  pookie: {
    name: "Pookie",
    emoji: "🌸",
    description: "Pink & purple galaxy vibes",
    bodyClass: "theme-pookie",

    // ── Typography profile ──────────────────────────────────────────────────
    // Airy and spacious — slightly larger scale, generous line-height.
    // Dancing Script display gives a soft, romantic feeling.
    typography: {
      scale:         1.05,   // Font-size multiplier applied to body base
      lineHeight:    1.72,   // Body line-height (rem-less unit)
      headingWeight: 800,    // weight for h1–h3
      bodyWeight:    400,    // weight for body copy
      monoWeight:    400,
      letterSpacing: "0.01em",
    },

    fonts: {
      google:  "https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&family=Playfair+Display:ital,wght@0,700;1,700&family=Dancing+Script:wght@500;700&display=swap",
      display: "'Dancing Script', cursive",
      body:    "'Nunito', sans-serif",
      mono:    "'DM Mono', monospace",
    },

    vars: {
      "--pookie-bg":        "#06020f",
      "--pookie-surface":   "rgba(168,85,247,0.08)",
      "--pookie-surface2":  "rgba(168,85,247,0.16)",
      "--pookie-pink":      "#f472b6",
      "--pookie-pink2":     "#ec4899",
      "--pookie-purple":    "#a855f7",
      "--pookie-purple2":   "#7c3aed",
      "--pookie-rose":      "#fb7185",
      "--pookie-text":      "#f8fafc",
      "--pookie-muted":     "#94a3b8",
      "--pookie-border":    "rgba(244,114,182,0.22)",
      "--pookie-border2":   "rgba(244,114,182,0.38)",
      "--pookie-radius":    "20px",
      "--pookie-radius-sm": "12px",
      "--pookie-shadow":    "0 8px 32px rgba(168,85,247,0.18)",
      "--pookie-shadow-h":  "0 14px 44px rgba(244,114,182,0.30)",
      "--pookie-glow":      "0 0 32px rgba(244,114,182,0.32)",
      "--pookie-font":      "'Nunito', sans-serif",
      "--pookie-display":   "'Dancing Script', cursive",
      "--theme-bg":         "#06020f",
      "--theme-surface":    "rgba(168,85,247,0.08)",
      "--theme-accent":     "#f472b6",
      "--theme-accent2":    "#a855f7",
      "--theme-text":       "#f8fafc",
      "--theme-muted":      "#94a3b8",
      "--theme-border":     "rgba(244,114,182,0.22)",
      "--theme-radius":     "20px",
      "--theme-radius-sm":  "12px",
      "--theme-shadow":     "0 8px 32px rgba(168,85,247,0.18)",
      "--theme-shadow-h":   "0 14px 44px rgba(244,114,182,0.30)",
      "--theme-glow":       "0 0 32px rgba(244,114,182,0.32)",
      "--theme-cursor-color": "#f472b6",
      // Typography tokens
      "--type-scale":       "1.05",
      "--type-line-height": "1.72",
      "--type-heading-weight": "800",
      "--type-body-weight": "400",
      "--type-letter-spacing": "0.01em",
    },

    overlayHTML: [
      '<canvas id="pookie-stars" style="position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:0;"></canvas>',
      '<div class="pookie-aurora pookie-aurora--1"></div>',
      '<div class="pookie-aurora pookie-aurora--2"></div>',
      '<div class="pookie-aurora pookie-aurora--3"></div>',
      '<div class="pookie-nebula pookie-nebula--1"></div>',
      '<div class="pookie-nebula pookie-nebula--2"></div>',
      '<div class="pookie-nebula pookie-nebula--3"></div>',
      '<div class="pookie-comet"></div>',
      '<div class="pookie-comet pookie-comet--2"></div>',
    ].join(""),

    overlayScript: [
      "(function() {",
      "  var canvas = document.getElementById('pookie-stars');",
      "  if (!canvas) return;",
      "  var ctx = canvas.getContext('2d');",
      "  var W, H, stars = [];",
      "  function resize() {",
      "    W = canvas.width  = window.innerWidth;",
      "    H = canvas.height = window.innerHeight;",
      "  }",
      "  function mkStars() {",
      "    stars = [];",
      "    for (var i = 0; i < 320; i++) {",
      "      var c = Math.random();",
      "      stars.push({",
      "        x: Math.random() * W, y: Math.random() * H,",
      "        r: Math.random() * 1.9 + 0.1,",
      "        o: Math.random() * 0.8 + 0.1,",
      "        s: Math.random() * 0.5 + 0.1,",
      "        phase: Math.random() * Math.PI * 2,",
      "        color: c > 0.7 ? '#f472b6' : c > 0.5 ? '#a855f7' : c > 0.3 ? '#c4b5fd' : '#fff'",
      "      });",
      "    }",
      "  }",
      "  var t = 0;",
      "  function draw() {",
      "    ctx.clearRect(0, 0, W, H);",
      "    t += 0.01;",
      "    for (var i = 0; i < stars.length; i++) {",
      "      var s = stars[i];",
      "      var tw = Math.sin(t * s.s * 60 / 60 + s.phase);",
      "      ctx.beginPath();",
      "      ctx.arc(s.x, s.y, s.r * (1 + 0.4 * tw), 0, Math.PI * 2);",
      "      ctx.fillStyle = s.color;",
      "      ctx.globalAlpha = s.o * (0.5 + 0.5 * tw);",
      "      ctx.fill();",
      "      if (s.o > 0.7 && s.r > 1.4) {",
      "        ctx.globalAlpha = 0.18 * (0.5 + 0.5 * tw);",
      "        var gl = s.r * 8;",
      "        for (var a = 0; a < 2; a++) {",
      "          ctx.save();",
      "          ctx.translate(s.x, s.y);",
      "          ctx.rotate(a * Math.PI / 2);",
      "          ctx.beginPath();",
      "          ctx.moveTo(-gl, 0); ctx.lineTo(gl, 0);",
      "          ctx.strokeStyle = s.color;",
      "          ctx.lineWidth = 0.5;",
      "          ctx.stroke();",
      "          ctx.restore();",
      "        }",
      "      }",
      "    }",
      "    ctx.globalAlpha = 1;",
      "    requestAnimationFrame(draw);",
      "  }",
      "  resize(); mkStars(); draw();",
      "  window.addEventListener('resize', function() { resize(); mkStars(); });",
      "})();",
    ].join("\n"),

    cursorScript: [
      "(function() {",
      "  document.querySelectorAll('.pookie-cursor,.pookie-cursor__trail,.pookie-sparkle').forEach(function(e) { e.remove(); });",
      "  var cursor = document.createElement('div');",
      "  cursor.className = 'pookie-cursor';",
      "  cursor.innerHTML = '<div class=\"pookie-cursor__ring\"></div><div class=\"pookie-cursor__dot\"></div>';",
      "  document.body.appendChild(cursor);",
      "  var trail = document.createElement('div');",
      "  trail.className = 'pookie-cursor__trail';",
      "  document.body.appendChild(trail);",
      "  var mx = -100, my = -100, tx = -100, ty = -100, sparkleTimer = 0;",
      "  var COLORS = ['#f472b6','#a855f7','#ec4899','#c4b5fd','#fbbf24','#fff'];",
      "  function spawnSparkle(x, y) {",
      "    var s = document.createElement('div');",
      "    s.className = 'pookie-sparkle';",
      "    var size = 3 + Math.random() * 5;",
      "    var dx = (Math.random() - 0.5) * 32;",
      "    var dy = (Math.random() - 0.5) * 32;",
      "    s.style.cssText = 'left:' + (x+dx) + 'px;top:' + (y+dy) + 'px;width:' + size + 'px;height:' + size + 'px;background:' + COLORS[Math.floor(Math.random()*COLORS.length)] + ';box-shadow:0 0 ' + (size*1.5) + 'px currentColor;';",
      "    document.body.appendChild(s);",
      "    setTimeout(function() { s.remove(); }, 700);",
      "  }",
      "  document.addEventListener('mousemove', function(e) {",
      "    mx = e.clientX; my = e.clientY;",
      "    cursor.style.left = mx + 'px'; cursor.style.top = my + 'px';",
      "    sparkleTimer++;",
      "    if (sparkleTimer % 4 === 0) spawnSparkle(mx, my);",
      "  });",
      "  setInterval(function() {",
      "    tx += (mx - tx) * 0.18; ty += (my - ty) * 0.18;",
      "    trail.style.left = tx + 'px'; trail.style.top = ty + 'px';",
      "  }, 16);",
      "  document.addEventListener('mousedown', function() {",
      "    var dot = cursor.querySelector('.pookie-cursor__dot');",
      "    if (dot) dot.style.transform = 'scale(0.6)';",
      "    for (var i = 0; i < 7; i++) spawnSparkle(mx, my);",
      "  });",
      "  document.addEventListener('mouseup', function() {",
      "    var dot = cursor.querySelector('.pookie-cursor__dot');",
      "    if (dot) dot.style.transform = 'scale(1)';",
      "  });",
      "})();",
    ].join("\n"),

    swatches:      ["#06020f", "#f472b6", "#a855f7", "#fb7185"],
    previewBg:     "#06020f",
    previewCard:   "rgba(168,85,247,0.14)",
    previewAccent: "#f472b6",
    dark: true,
  },


  // ══════════════════════════════════════════════════════════════════════════
  // 2. AESTHETIC  ·  Warm Parchment × Moody Autumnal — Upgraded
  //    Cursor: antique quill pen with ink dot trail
  // ══════════════════════════════════════════════════════════════════════════
  aesthetic: {
    name: "Aesthetic",
    emoji: "🍂",
    description: "Warm parchment & golden tones",
    bodyClass: "theme-aesthetic",

    // ── Typography profile ──────────────────────────────────────────────────
    // Dense and literary — slightly smaller scale, tighter tracking.
    // Serif body gives a book-page feel; long-form reading rhythm.
    typography: {
      scale:         0.98,
      lineHeight:    1.80,   // Serifs need more vertical breathing room
      headingWeight: 700,
      bodyWeight:    400,
      monoWeight:    400,
      letterSpacing: "0.005em",
    },

    fonts: {
      google:  "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,600;0,700;1,400;1,600&family=Lora:ital,wght@0,400;0,600;1,400&family=IM+Fell+English:ital@0;1&display=swap",
      display: "'IM Fell English', serif",
      body:    "'Lora', serif",
      mono:    "'Courier Prime', monospace",
    },

    vars: {
      "--pookie-bg":        "#f5efe4",
      "--pookie-surface":   "rgba(196,147,100,0.12)",
      "--pookie-surface2":  "rgba(196,147,100,0.24)",
      "--pookie-pink":      "#b5673d",
      "--pookie-pink2":     "#9c5030",
      "--pookie-purple":    "#8b6347",
      "--pookie-purple2":   "#6b4a30",
      "--pookie-rose":      "#c96442",
      "--pookie-text":      "#2c1f12",
      "--pookie-muted":     "#7a6048",
      "--pookie-border":    "rgba(181,103,61,0.25)",
      "--pookie-border2":   "rgba(181,103,61,0.45)",
      "--pookie-radius":    "4px",
      "--pookie-radius-sm": "2px",
      "--pookie-shadow":    "0 2px 14px rgba(100,60,20,0.15)",
      "--pookie-shadow-h":  "0 8px 28px rgba(100,60,20,0.22)",
      "--pookie-glow":      "0 0 22px rgba(185,110,55,0.30)",
      "--pookie-font":      "'Lora', serif",
      "--pookie-display":   "'IM Fell English', serif",
      "--theme-bg":         "#f5efe4",
      "--theme-surface":    "rgba(196,147,100,0.12)",
      "--theme-accent":     "#b5673d",
      "--theme-accent2":    "#8b6347",
      "--theme-text":       "#2c1f12",
      "--theme-muted":      "#7a6048",
      "--theme-border":     "rgba(181,103,61,0.25)",
      "--theme-radius":     "4px",
      "--theme-radius-sm":  "2px",
      "--theme-shadow":     "0 2px 14px rgba(100,60,20,0.15)",
      "--theme-shadow-h":   "0 8px 28px rgba(100,60,20,0.22)",
      "--theme-glow":       "0 0 22px rgba(185,110,55,0.30)",
      "--theme-cursor-color": "#b5673d",
      "--aesthetic-grain-opacity": "0.055",
      // Typography tokens
      "--type-scale":       "0.98",
      "--type-line-height": "1.80",
      "--type-heading-weight": "700",
      "--type-body-weight": "400",
      "--type-letter-spacing": "0.005em",
    },

    overlayHTML: [
      '<div class="aesthetic-grain"></div>',
      '<div class="aesthetic-vignette"></div>',
      '<div class="aesthetic-warmlight"></div>',
      '<div class="aesthetic-watercolor aesthetic-watercolor--1"></div>',
      '<div class="aesthetic-watercolor aesthetic-watercolor--2"></div>',
      '<div class="aesthetic-watercolor aesthetic-watercolor--3"></div>',
      '<svg class="aesthetic-botanicals" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600" preserveAspectRatio="xMidYMid slice">',
      '<g opacity="0.08" transform="translate(28,410) rotate(-22)">',
      '<line x1="0" y1="0" x2="0" y2="-120" stroke="#5a3e28" stroke-width="1.8"/>',
      '<path d="M0,-8 Q28,-28 22,-60 Q2,-38 0,-8Z" fill="#5a3e28"/>',
      '<path d="M0,-8 Q-26,-26 -18,-58 Q2,-36 0,-8Z" fill="#5a3e28"/>',
      '<path d="M0,-22 Q32,-38 26,-72 Q4,-50 0,-22Z" fill="#5a3e28"/>',
      '<path d="M0,-22 Q-28,-34 -22,-68 Q4,-48 0,-22Z" fill="#5a3e28"/>',
      '<path d="M0,-38 Q26,-50 20,-84 Q2,-60 0,-38Z" fill="#5a3e28"/>',
      '<path d="M0,-38 Q-24,-46 -18,-80 Q4,-58 0,-38Z" fill="#5a3e28"/>',
      '</g>',
      '<g opacity="0.075" transform="translate(724,58) rotate(12)">',
      '<path d="M0,0 Q14,-20 0,-34 Q-14,-20 0,0Z" fill="#8b4a30"/>',
      '<path d="M0,0 Q20,-6 24,8 Q12,20 0,0Z" fill="#9c5535"/>',
      '<path d="M0,0 Q-20,-6 -24,8 Q-12,20 0,0Z" fill="#9c5535"/>',
      '<path d="M0,30 Q2,55 -6,70" stroke="#5a3e28" stroke-width="1.4" fill="none"/>',
      '</g>',
      '</svg>',
    ].join(""),

    overlayScript: "",

    cursorScript: [
      "(function() {",
      "  document.querySelectorAll('.aesthetic-cursor,.aesthetic-ink-dot,.aesthetic-ink-trail').forEach(function(e) { e.remove(); });",
      "  var cursor = document.createElement('div');",
      "  cursor.className = 'aesthetic-cursor';",
      "  cursor.innerHTML = '<svg width=\"32\" height=\"36\" viewBox=\"0 0 32 36\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M28,2 C20,2 6,18 2,34\" stroke=\"#5a3e28\" stroke-width=\"1\" fill=\"none\" opacity=\"0.7\"/><path d=\"M28,2 C32,6 30,14 20,20 C22,12 26,6 28,2Z\" fill=\"#c8a882\" opacity=\"0.6\"/><path d=\"M28,2 C24,8 18,14 14,22 C18,14 24,8 28,2Z\" fill=\"#b89060\" opacity=\"0.5\"/><path d=\"M2,34 L5,30 L4,32Z\" fill=\"#2c1f12\" opacity=\"0.8\"/><ellipse cx=\"2.5\" cy=\"34.5\" rx=\"1.2\" ry=\"1.5\" fill=\"#1a0f08\" opacity=\"0.55\"/></svg>';",
      "  document.body.appendChild(cursor);",
      "  var inkDot = document.createElement('div');",
      "  inkDot.className = 'aesthetic-ink-dot';",
      "  document.body.appendChild(inkDot);",
      "  var mx = -100, my = -100, ix = -100, iy = -100;",
      "  var lastTrailX = -200, lastTrailY = -200, trailTimer = 0;",
      "  function spawnInkTrail(x, y) {",
      "    var t = document.createElement('div');",
      "    t.className = 'aesthetic-ink-trail';",
      "    var size = 4 + Math.random() * 6;",
      "    t.style.cssText = 'left:' + x + 'px;top:' + y + 'px;width:' + size + 'px;height:' + size + 'px;';",
      "    document.body.appendChild(t);",
      "    setTimeout(function() { t.remove(); }, 1200);",
      "  }",
      "  document.addEventListener('mousemove', function(e) {",
      "    mx = e.clientX; my = e.clientY;",
      "    cursor.style.left = mx + 'px'; cursor.style.top = my + 'px';",
      "    trailTimer++;",
      "    if (trailTimer % 6 === 0) {",
      "      var dx = mx - lastTrailX, dy = my - lastTrailY;",
      "      if (Math.sqrt(dx*dx+dy*dy) > 15) {",
      "        spawnInkTrail(mx, my);",
      "        lastTrailX = mx; lastTrailY = my;",
      "      }",
      "    }",
      "  });",
      "  setInterval(function() {",
      "    ix += (mx - ix) * 0.14; iy += (my - iy) * 0.14;",
      "    inkDot.style.left = ix + 'px'; inkDot.style.top = iy + 'px';",
      "  }, 16);",
      "  document.addEventListener('mousedown', function() {",
      "    cursor.style.transform = 'translate(-6px,-2px) rotate(45deg) scale(0.85)';",
      "    spawnInkTrail(mx, my); spawnInkTrail(mx+3, my+3);",
      "  });",
      "  document.addEventListener('mouseup', function() {",
      "    cursor.style.transform = 'translate(-6px,-2px) rotate(45deg) scale(1)';",
      "  });",
      "})();",
    ].join("\n"),

    swatches:      ["#f5efe4", "#b5673d", "#8b6347", "#c96442"],
    previewBg:     "#f5efe4",
    previewCard:   "rgba(196,147,100,0.20)",
    previewAccent: "#b5673d",
    dark: false,
  },


  // ══════════════════════════════════════════════════════════════════════════
  // 3. STELLER  ·  Deep Space Indigo × Cyan — Upgraded
  //    Cursor: animated sci-fi targeting reticle
  // ══════════════════════════════════════════════════════════════════════════
  steller: {
    name: "Steller",
    emoji: "🚀",
    description: "Deep space indigo & cyan",
    bodyClass: "theme-steller",

    // ── Typography profile ──────────────────────────────────────────────────
    // Technical and precise — neutral scale, tighter line-height.
    // Geometric sans with mono accents for the HUD/data feel.
    typography: {
      scale:         1.00,
      lineHeight:    1.62,
      headingWeight: 700,
      bodyWeight:    400,
      monoWeight:    500,    // Slightly bolder mono for data readability
      letterSpacing: "0.02em",
    },

    fonts: {
      google:  "https://fonts.googleapis.com/css2?family=Oxanium:wght@400;500;600;700;800&family=Exo+2:ital,wght@0,300;0,400;0,600;0,700;1,400&family=Share+Tech+Mono&display=swap",
      display: "'Oxanium', sans-serif",
      body:    "'Exo 2', sans-serif",
      mono:    "'Share Tech Mono', monospace",
    },

    vars: {
      "--pookie-bg":        "#020510",
      "--pookie-surface":   "rgba(56,189,248,0.07)",
      "--pookie-surface2":  "rgba(56,189,248,0.14)",
      "--pookie-pink":      "#38bdf8",
      "--pookie-pink2":     "#0ea5e9",
      "--pookie-purple":    "#818cf8",
      "--pookie-purple2":   "#6366f1",
      "--pookie-rose":      "#34d399",
      "--pookie-text":      "#e0f2fe",
      "--pookie-muted":     "#7aadcc",
      "--pookie-border":    "rgba(56,189,248,0.20)",
      "--pookie-border2":   "rgba(56,189,248,0.40)",
      "--pookie-radius":    "6px",
      "--pookie-radius-sm": "3px",
      "--pookie-shadow":    "0 4px 24px rgba(56,189,248,0.14)",
      "--pookie-shadow-h":  "0 12px 40px rgba(56,189,248,0.28)",
      "--pookie-glow":      "0 0 28px rgba(56,189,248,0.38)",
      "--pookie-font":      "'Exo 2', sans-serif",
      "--pookie-display":   "'Oxanium', sans-serif",
      "--theme-bg":         "#020510",
      "--theme-surface":    "rgba(56,189,248,0.07)",
      "--theme-accent":     "#38bdf8",
      "--theme-accent2":    "#818cf8",
      "--theme-text":       "#e0f2fe",
      "--theme-muted":      "#7aadcc",
      "--theme-border":     "rgba(56,189,248,0.20)",
      "--theme-radius":     "6px",
      "--theme-radius-sm":  "3px",
      "--theme-shadow":     "0 4px 24px rgba(56,189,248,0.14)",
      "--theme-shadow-h":   "0 12px 40px rgba(56,189,248,0.28)",
      "--theme-glow":       "0 0 28px rgba(56,189,248,0.38)",
      "--theme-cursor-color": "#38bdf8",
      "--steller-scan-color": "rgba(56,189,248,0.04)",
      // Typography tokens
      "--type-scale":       "1.00",
      "--type-line-height": "1.62",
      "--type-heading-weight": "700",
      "--type-body-weight": "400",
      "--type-letter-spacing": "0.02em",
    },

    overlayHTML: [
      '<canvas id="steller-space" style="position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:0;"></canvas>',
      '<div class="steller-scanlines"></div>',
      '<div class="steller-planet">',
      '  <div class="steller-planet-ring steller-planet-ring--3"></div>',
      '  <div class="steller-planet-ring steller-planet-ring--2"></div>',
      '  <div class="steller-planet-ring steller-planet-ring--1"></div>',
      '  <div class="steller-planet-core"></div>',
      '</div>',
      '<div class="steller-hud-corner steller-hud-corner--tl"></div>',
      '<div class="steller-hud-corner steller-hud-corner--br"></div>',
      '<div class="steller-hud-corner steller-hud-corner--tr"></div>',
      '<div class="steller-hud-corner steller-hud-corner--bl"></div>',
      '<div class="steller-hud-data"><div>SYS: ONLINE</div><div>THM: STELLER</div></div>',
      '<div class="steller-hud-data-br"><div>FIELD: ACTIVE</div><div>SYNC: 100%</div></div>',
    ].join(""),

    // NOTE: overlayScript for steller is long — preserved verbatim from v4.0.
    // The canvas star/nebula/streak/constellation renderer lives here.
    overlayScript: [
      "(function() {",
      "  var canvas = document.getElementById('steller-space');",
      "  if (!canvas) return;",
      "  var ctx = canvas.getContext('2d');",
      "  var W, H, stars = [], nebula = [], streaks = [], constellations = [];",
      "  function resize() {",
      "    W = canvas.width  = window.innerWidth;",
      "    H = canvas.height = window.innerHeight;",
      "  }",
      "  function mkStars() {",
      "    stars = []; nebula = []; streaks = []; constellations = [];",
      "    for (var i = 0; i < 400; i++) {",
      "      var c = Math.random();",
      "      stars.push({",
      "        x: Math.random()*W, y: Math.random()*H,",
      "        r: Math.random()*1.8+0.1,",
      "        o: Math.random()*0.85+0.1,",
      "        s: Math.random()*0.4+0.05,",
      "        phase: Math.random()*Math.PI*2,",
      "        color: c>0.75?'#38bdf8':c>0.55?'#818cf8':c>0.35?'#c7d2fe':'#e0f2fe'",
      "      });",
      "    }",
      "    for (var j = 0; j < 5; j++) {",
      "      nebula.push({",
      "        x: Math.random()*W, y: Math.random()*H,",
      "        r: 120+Math.random()*200,",
      "        color: Math.random()>0.5?'rgba(56,189,248,':'rgba(129,140,248,'",
      "      });",
      "    }",
      "    for (var k = 0; k < 3; k++) {",
      "      var pts = [];",
      "      var cx2 = Math.random()*W, cy2 = Math.random()*H;",
      "      for (var p = 0; p < 4+Math.floor(Math.random()*4); p++) {",
      "        pts.push({x:cx2+(Math.random()-0.5)*260,y:cy2+(Math.random()-0.5)*180});",
      "      }",
      "      constellations.push(pts);",
      "    }",
      "  }",
      "  var t = 0;",
      "  function draw() {",
      "    ctx.clearRect(0,0,W,H);",
      "    t += 0.008;",
      "    for (var n = 0; n < nebula.length; n++) {",
      "      var nb = nebula[n];",
      "      var g = ctx.createRadialGradient(nb.x,nb.y,0,nb.x,nb.y,nb.r);",
      "      g.addColorStop(0,nb.color+'0.06)');",
      "      g.addColorStop(1,nb.color+'0)');",
      "      ctx.beginPath();",
      "      ctx.arc(nb.x,nb.y,nb.r,0,Math.PI*2);",
      "      ctx.fillStyle = g;",
      "      ctx.fill();",
      "    }",
      "    for (var ci = 0; ci < constellations.length; ci++) {",
      "      var pts2 = constellations[ci];",
      "      ctx.beginPath();",
      "      ctx.moveTo(pts2[0].x,pts2[0].y);",
      "      for (var pi2 = 1; pi2 < pts2.length; pi2++) ctx.lineTo(pts2[pi2].x,pts2[pi2].y);",
      "      ctx.strokeStyle='rgba(56,189,248,0.07)'; ctx.lineWidth=0.7; ctx.stroke();",
      "    }",
      "    for (var i = 0; i < stars.length; i++) {",
      "      var s = stars[i];",
      "      var tw = Math.sin(t*s.s*60/60+s.phase);",
      "      ctx.beginPath();",
      "      ctx.arc(s.x,s.y,s.r*(1+0.35*tw),0,Math.PI*2);",
      "      ctx.fillStyle = s.color;",
      "      ctx.globalAlpha = s.o*(0.45+0.55*tw);",
      "      ctx.fill();",
      "      if (s.o>0.75 && s.r>1.3) {",
      "        ctx.globalAlpha=0.15*(0.5+0.5*tw);",
      "        var gl2=s.r*7;",
      "        for (var a=0;a<2;a++){",
      "          ctx.save(); ctx.translate(s.x,s.y); ctx.rotate(a*Math.PI/2);",
      "          ctx.beginPath(); ctx.moveTo(-gl2,0); ctx.lineTo(gl2,0);",
      "          ctx.strokeStyle=s.color; ctx.lineWidth=0.4; ctx.stroke(); ctx.restore();",
      "        }",
      "      }",
      "    }",
      "    ctx.globalAlpha=1;",
      "    if (Math.random()<0.005) {",
      "      streaks.push({x:Math.random()*W,y:Math.random()*H*0.5,len:60+Math.random()*120,o:1,sp:4+Math.random()*8});",
      "    }",
      "    for (var si = streaks.length-1; si >= 0; si--) {",
      "      var sr = streaks[si];",
      "      ctx.save(); ctx.globalAlpha=sr.o*0.7;",
      "      ctx.beginPath(); ctx.moveTo(sr.x,sr.y); ctx.lineTo(sr.x+sr.len,sr.y+sr.len*0.2);",
      "      ctx.strokeStyle='rgba(56,189,248,0.8)'; ctx.lineWidth=1.2; ctx.stroke(); ctx.restore();",
      "      sr.x+=sr.sp; sr.y+=sr.sp*0.2; sr.o-=0.03;",
      "      if (sr.o<=0) streaks.splice(si,1);",
      "    }",
      "    requestAnimationFrame(draw);",
      "  }",
      "  resize(); mkStars(); draw();",
      "  window.addEventListener('resize', function(){ resize(); mkStars(); });",
      "})();",
    ].join("\n"),

    cursorScript: [
      "(function() {",
      "  document.querySelectorAll('.steller-cursor,.steller-cursor-h-line,.steller-cursor-v-line,.steller-cursor-scan').forEach(function(e) { e.remove(); });",
      "  var cur = document.createElement('div'); cur.className='steller-cursor';",
      "  cur.innerHTML='<div class=\"steller-cursor__outer\"><div class=\"steller-cursor__tl\"></div><div class=\"steller-cursor__tr\"></div><div class=\"steller-cursor__bl\"></div><div class=\"steller-cursor__br\"></div></div><div class=\"steller-cursor__inner\"></div><div class=\"steller-cursor__dot\"></div>';",
      "  document.body.appendChild(cur);",
      "  var hLine = document.createElement('div'); hLine.className='steller-cursor-h-line'; document.body.appendChild(hLine);",
      "  var vLine = document.createElement('div'); vLine.className='steller-cursor-v-line'; document.body.appendChild(vLine);",
      "  var scan = document.createElement('div'); scan.className='steller-cursor-scan'; document.body.appendChild(scan);",
      "  var mx=-100, my=-100;",
      "  document.addEventListener('mousemove', function(e) {",
      "    mx=e.clientX; my=e.clientY;",
      "    cur.style.left=mx+'px'; cur.style.top=my+'px';",
      "    hLine.style.top=my+'px'; vLine.style.left=mx+'px';",
      "    scan.style.top=my+'px';",
      "  });",
      "  document.addEventListener('mousedown', function() {",
      "    var d=cur.querySelector('.steller-cursor__dot'); if(d) d.style.background='rgba(56,189,248,1)';",
      "  });",
      "  document.addEventListener('mouseup', function() {",
      "    var d=cur.querySelector('.steller-cursor__dot'); if(d) d.style.background='';",
      "  });",
      "})();",
    ].join("\n"),

    swatches:      ["#020510", "#38bdf8", "#818cf8", "#34d399"],
    previewBg:     "#020510",
    previewCard:   "rgba(56,189,248,0.10)",
    previewAccent: "#38bdf8",
    dark: true,
  },


  // ══════════════════════════════════════════════════════════════════════════
  // 4. NOTEBOOK  ·  College-ruled paper + red margin + spiral binding
  //    Cursor: fountain pen nib with ink stroke trail
  // ══════════════════════════════════════════════════════════════════════════
  notebook: {
    name: "Notebook",
    emoji: "📓",
    description: "College-ruled paper & handwritten ink",
    bodyClass: "theme-notebook",

    // ── Typography profile ──────────────────────────────────────────────────
    // Handwritten and organic — slightly larger scale for legibility.
    // Cursive body matches the ruled-paper aesthetic perfectly.
    typography: {
      scale:         1.02,
      lineHeight:    1.90,   // Match the ruled-line rhythm of the bg
      headingWeight: 700,
      bodyWeight:    400,
      monoWeight:    400,
      letterSpacing: "0.00em",
    },

    fonts: {
      google:  "https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&family=Caveat+Brush&family=Kalam:wght@300;400;700&family=Patrick+Hand&display=swap",
      display: "'Caveat Brush', cursive",
      body:    "'Kalam', cursive",
      mono:    "'Patrick Hand', cursive",
    },

    vars: {
      "--pookie-bg":        "#f8f6ef",
      "--pookie-surface":   "rgba(255,255,255,0.75)",
      "--pookie-surface2":  "rgba(255,255,255,0.92)",
      "--pookie-pink":      "#1a3a6b",
      "--pookie-pink2":     "#0f2449",
      "--pookie-purple":    "#2855a0",
      "--pookie-purple2":   "#1e3f7a",
      "--pookie-rose":      "#c0392b",
      "--pookie-text":      "#1c1c2e",
      "--pookie-muted":     "#6b7280",
      "--pookie-border":    "rgba(26,58,107,0.18)",
      "--pookie-border2":   "rgba(26,58,107,0.34)",
      "--pookie-radius":    "2px",
      "--pookie-radius-sm": "1px",
      "--pookie-shadow":    "0 1px 6px rgba(0,0,0,0.10)",
      "--pookie-shadow-h":  "0 4px 20px rgba(0,0,0,0.16)",
      "--pookie-glow":      "0 0 16px rgba(26,58,107,0.20)",
      "--pookie-font":      "'Kalam', cursive",
      "--pookie-display":   "'Caveat Brush', cursive",
      "--theme-bg":         "#f8f6ef",
      "--theme-surface":    "rgba(255,255,255,0.75)",
      "--theme-accent":     "#1a3a6b",
      "--theme-accent2":    "#2855a0",
      "--theme-text":       "#1c1c2e",
      "--theme-muted":      "#6b7280",
      "--theme-border":     "rgba(26,58,107,0.18)",
      "--theme-radius":     "2px",
      "--theme-radius-sm":  "1px",
      "--theme-shadow":     "0 1px 6px rgba(0,0,0,0.10)",
      "--theme-shadow-h":   "0 4px 20px rgba(0,0,0,0.16)",
      "--theme-glow":       "0 0 16px rgba(26,58,107,0.20)",
      "--theme-cursor-color": "#1a3a6b",
      "--nb-line-color":    "rgba(147,197,253,0.55)",
      "--nb-margin-color":  "rgba(220,38,38,0.35)",
      "--nb-line-height":   "32px",
      "--nb-margin-left":   "72px",
      "--nb-paper":         "#faf8f1",
      // Typography tokens
      "--type-scale":       "1.02",
      "--type-line-height": "1.90",
      "--type-heading-weight": "700",
      "--type-body-weight": "400",
      "--type-letter-spacing": "0.00em",
    },

    overlayHTML: (function() {
      var coils = "";
      for (var i = 0; i < 24; i++) {
        coils += '<div class="nb-coil" style="left:' + (i * 36 + 12) + 'px"></div>';
      }
      return [
        '<div class="nb-page-shell">',
        '  <div class="nb-spiral">' + coils + '</div>',
        '  <div class="nb-rules"></div>',
        '  <div class="nb-margin-line"></div>',
        '  <div class="nb-margin-line-2"></div>',
        '  <div class="nb-hole nb-hole--1"><div class="nb-hole-ring"></div></div>',
        '  <div class="nb-hole nb-hole--2"><div class="nb-hole-ring"></div></div>',
        '  <div class="nb-hole nb-hole--3"><div class="nb-hole-ring"></div></div>',
        '  <div class="nb-page-curl"></div>',
        '  <div class="nb-coffee-ring"></div>',
        '  <div class="nb-ink-blot"></div>',
        '  <div class="nb-date-stamp" id="nb-date"></div>',
        '</div>',
      ].join("");
    })(),

    overlayScript: [
      "(function() {",
      "  var el = document.getElementById('nb-date');",
      "  if (el) {",
      "    var now = new Date();",
      "    el.textContent = now.toLocaleDateString('en-US', { month:'short', day:'numeric', year:'numeric' });",
      "  }",
      "})();",
    ].join("\n"),

    cursorScript: [
      "(function() {",
      "  document.querySelectorAll('.notebook-cursor,.notebook-ink-stroke').forEach(function(e) { e.remove(); });",
      "  var cursor = document.createElement('div');",
      "  cursor.className = 'notebook-cursor';",
      "  cursor.innerHTML = '<svg width=\"28\" height=\"34\" viewBox=\"0 0 28 34\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"10\" y=\"0\" width=\"8\" height=\"22\" rx=\"2\" fill=\"#1a3a6b\" opacity=\"0.85\"/><rect x=\"9\" y=\"18\" width=\"10\" height=\"3\" rx=\"1\" fill=\"#2855a0\" opacity=\"0.7\"/><polygon points=\"10,21 18,21 14,34\" fill=\"#0f2449\" opacity=\"0.9\"/><line x1=\"14\" y1=\"21\" x2=\"14\" y2=\"33\" stroke=\"#4a7abf\" stroke-width=\"0.5\" opacity=\"0.6\"/><rect x=\"12\" y=\"3\" width=\"2\" height=\"12\" rx=\"1\" fill=\"rgba(255,255,255,0.18)\"/><ellipse cx=\"14\" cy=\"33.5\" rx=\"1.5\" ry=\"1\" fill=\"#0f2449\" opacity=\"0.7\"/></svg>';",
      "  document.body.appendChild(cursor);",
      "  var mx = -100, my = -100;",
      "  var lastStrokeX = -999, lastStrokeY = -999, strokeTimer = 0;",
      "  function spawnStroke(x, y, px, py) {",
      "    var dx = x-px, dy = y-py;",
      "    var len = Math.sqrt(dx*dx+dy*dy);",
      "    if (len < 2) return;",
      "    var angle = Math.atan2(dy, dx);",
      "    var stroke = document.createElement('div');",
      "    stroke.className = 'notebook-ink-stroke';",
      "    stroke.style.cssText = 'left:'+px+'px;top:'+py+'px;width:'+len+'px;height:'+(1+Math.random()*1.5)+'px;transform:rotate('+angle+'rad);border-radius:1px;';",
      "    document.body.appendChild(stroke);",
      "    setTimeout(function() { stroke.remove(); }, 1400);",
      "  }",
      "  document.addEventListener('mousemove', function(e) {",
      "    mx = e.clientX; my = e.clientY;",
      "    cursor.style.left = mx+'px'; cursor.style.top = my+'px';",
      "    strokeTimer++;",
      "    if (strokeTimer % 3 === 0) {",
      "      if (lastStrokeX > -900) spawnStroke(mx, my, lastStrokeX, lastStrokeY);",
      "      lastStrokeX = mx; lastStrokeY = my;",
      "    }",
      "  });",
      "  document.addEventListener('mousedown', function() {",
      "    cursor.style.transform = 'translate(-3px,-3px) rotate(45deg) scale(0.88)';",
      "  });",
      "  document.addEventListener('mouseup', function() {",
      "    cursor.style.transform = 'translate(-3px,-3px) rotate(45deg) scale(1)';",
      "  });",
      "})();",
    ].join("\n"),

    swatches:      ["#f8f6ef", "#1a3a6b", "#2855a0", "#c0392b"],
    previewBg:     "#f8f6ef",
    previewCard:   "rgba(255,255,255,0.85)",
    previewAccent: "#1a3a6b",
    dark: false,
  },


  // ══════════════════════════════════════════════════════════════════════════
  // 5. GRAPH PAPER  ·  Clean white × engineering blue
  //    Cursor: full-viewport precision crosshair with coordinate label
  // ══════════════════════════════════════════════════════════════════════════
  graphpaper: {
    name: "Graph Paper",
    emoji: "📐",
    description: "Engineering graph paper — precise & minimal",
    bodyClass: "theme-graphpaper",

    // ── Typography profile ──────────────────────────────────────────────────
    // Compact and engineering-precise — slightly smaller scale, tight rhythm.
    // IBM Plex family gives a technical, monospace-adjacent feel throughout.
    typography: {
      scale:         0.95,
      lineHeight:    1.55,   // Compact — matches engineering notation density
      headingWeight: 600,    // Less heavy — engineering labels, not poetry
      bodyWeight:    400,
      monoWeight:    400,
      letterSpacing: "0.03em",
    },

    fonts: {
      google:  "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400&family=IBM+Plex+Mono:wght@300;400;500;600&family=IBM+Plex+Serif:ital,wght@0,400;0,600;1,400&display=swap",
      display: "'IBM Plex Serif', serif",
      body:    "'IBM Plex Sans', sans-serif",
      mono:    "'IBM Plex Mono', monospace",
    },

    vars: {
      "--pookie-bg":        "#fefefe",
      "--pookie-surface":   "rgba(37,99,235,0.04)",
      "--pookie-surface2":  "rgba(37,99,235,0.09)",
      "--pookie-pink":      "#1d4ed8",
      "--pookie-pink2":     "#1e40af",
      "--pookie-purple":    "#7c3aed",
      "--pookie-purple2":   "#6d28d9",
      "--pookie-rose":      "#dc2626",
      "--pookie-text":      "#0a0f1e",
      "--pookie-muted":     "#6b7280",
      "--pookie-border":    "rgba(37,99,235,0.18)",
      "--pookie-border2":   "rgba(37,99,235,0.34)",
      "--pookie-radius":    "3px",
      "--pookie-radius-sm": "2px",
      "--pookie-shadow":    "0 1px 4px rgba(0,0,0,0.06)",
      "--pookie-shadow-h":  "0 4px 18px rgba(0,0,0,0.10)",
      "--pookie-glow":      "0 0 16px rgba(37,99,235,0.22)",
      "--pookie-font":      "'IBM Plex Sans', sans-serif",
      "--pookie-display":   "'IBM Plex Serif', serif",
      "--theme-bg":         "#fefefe",
      "--theme-surface":    "rgba(37,99,235,0.04)",
      "--theme-accent":     "#1d4ed8",
      "--theme-accent2":    "#7c3aed",
      "--theme-text":       "#0a0f1e",
      "--theme-muted":      "#6b7280",
      "--theme-border":     "rgba(37,99,235,0.18)",
      "--theme-radius":     "3px",
      "--theme-radius-sm":  "2px",
      "--theme-shadow":     "0 1px 4px rgba(0,0,0,0.06)",
      "--theme-shadow-h":   "0 4px 18px rgba(0,0,0,0.10)",
      "--theme-glow":       "0 0 16px rgba(37,99,235,0.22)",
      "--theme-cursor-color": "#1d4ed8",
      "--gp-minor":         "rgba(147,197,253,0.52)",
      "--gp-major":         "rgba(37,99,235,0.24)",
      "--gp-cell":          "20px",
      "--gp-axis":          "rgba(37,99,235,0.55)",
      "--gp-label":         "rgba(37,99,235,0.38)",
      // Typography tokens
      "--type-scale":       "0.95",
      "--type-line-height": "1.55",
      "--type-heading-weight": "600",
      "--type-body-weight": "400",
      "--type-letter-spacing": "0.03em",
    },

    overlayHTML: [
      '<div class="gp-grid-layer"></div>',
      '<canvas id="gp-canvas" class="gp-canvas"></canvas>',
      '<div class="gp-axis-x" id="gp-ax"></div>',
      '<div class="gp-axis-x-label">x</div>',
      '<div class="gp-axis-y" id="gp-ay"></div>',
      '<div class="gp-axis-y-label">y</div>',
      '<div class="gp-origin"><div class="gp-origin-dot"></div><div class="gp-origin-label">O (0,0)</div></div>',
      '<div class="gp-ticks-x" id="gp-ticks-x"></div>',
      '<div class="gp-ticks-y" id="gp-ticks-y"></div>',
      '<div class="gp-corner-mark gp-corner-mark--tl"><span class="gp-label-text">StudyBuddy v4.1 \u00b7 \u0192(x)</span></div>',
      '<div class="gp-annotations">',
      '  <div class="gp-annotation gp-annotation--1"><span class="gp-note-text">Graph Paper Mode</span><div class="gp-note-line"></div></div>',
      '  <div class="gp-annotation gp-annotation--2"><div class="gp-delta-mark">\u0394</div><span class="gp-note-text">scale: 20px/unit</span></div>',
      '</div>',
    ].join(""),

    overlayScript: [
      "(function() {",
      "  var CELL = 20;",
      "  var txCon = document.getElementById('gp-ticks-x');",
      "  var tyCon = document.getElementById('gp-ticks-y');",
      "  if (txCon && tyCon) {",
      "    var W = window.innerWidth, H = window.innerHeight;",
      "    var cx = W/2, cy = H/2;",
      "    for (var x = CELL; x < W/2; x += CELL) {",
      "      var major = (x % 100 === 0);",
      "      var pxArr = [cx+x, cx-x];",
      "      for (var pi = 0; pi < pxArr.length; pi++) {",
      "        var px = pxArr[pi];",
      "        var tick = document.createElement('div');",
      "        tick.className = 'gp-tick-mark gp-tick-mark--x' + (major ? ' gp-tick-mark--x-major' : '');",
      "        tick.style.left = px+'px';",
      "        txCon.appendChild(tick);",
      "        if (major) {",
      "          var lbl = document.createElement('span');",
      "          lbl.style.cssText = 'position:absolute;left:'+px+'px;top:10px;transform:translateX(-50%);font-family:IBM Plex Mono,monospace;font-size:8px;color:rgba(37,99,235,0.38);white-space:nowrap;pointer-events:none;';",
      "          lbl.textContent = Math.round((px-cx)/CELL);",
      "          txCon.appendChild(lbl);",
      "        }",
      "      }",
      "    }",
      "    for (var y = CELL; y < H/2; y += CELL) {",
      "      var majorY = (y % 100 === 0);",
      "      var pyArr = [cy+y, cy-y];",
      "      for (var yi = 0; yi < pyArr.length; yi++) {",
      "        var py = pyArr[yi];",
      "        var tickY = document.createElement('div');",
      "        tickY.className = 'gp-tick-mark gp-tick-mark--y' + (majorY ? ' gp-tick-mark--y-major' : '');",
      "        tickY.style.top = py+'px';",
      "        tyCon.appendChild(tickY);",
      "        if (majorY) {",
      "          var lblY = document.createElement('span');",
      "          lblY.style.cssText = 'position:absolute;top:'+py+'px;left:10px;transform:translateY(-50%);font-family:IBM Plex Mono,monospace;font-size:8px;color:rgba(37,99,235,0.38);white-space:nowrap;pointer-events:none;';",
      "          lblY.textContent = -Math.round((py-cy)/CELL);",
      "          tyCon.appendChild(lblY);",
      "        }",
      "      }",
      "    }",
      "  }",
      "  var canvas = document.getElementById('gp-canvas');",
      "  if (!canvas) return;",
      "  var ctx = canvas.getContext('2d');",
      "  var CW, CH;",
      "  function resize() {",
      "    CW = canvas.width = window.innerWidth;",
      "    CH = canvas.height = window.innerHeight;",
      "  }",
      "  var SCALE = 20, ft = 0;",
      "  function drawFn(ccx, ccy, fn, color, alpha, lineWidth) {",
      "    ctx.beginPath();",
      "    ctx.strokeStyle = color; ctx.lineWidth = lineWidth; ctx.globalAlpha = alpha;",
      "    var first = true;",
      "    for (var px = 0; px <= CW; px += 1.5) {",
      "      var fx = (px-ccx)/SCALE;",
      "      var fy;",
      "      try { fy = fn(fx); } catch(e) { continue; }",
      "      if (!isFinite(fy) || Math.abs(fy)>200) { first=true; continue; }",
      "      var sy = ccy - fy*SCALE;",
      "      if (first) { ctx.moveTo(px,sy); first=false; } else { ctx.lineTo(px,sy); }",
      "    }",
      "    ctx.stroke(); ctx.globalAlpha = 1;",
      "  }",
      "  function draw() {",
      "    ctx.clearRect(0,0,CW,CH);",
      "    ft += 0.008;",
      "    var ccx = CW/2, ccy = CH/2;",
      "    drawFn(ccx,ccy,function(x){return Math.sin(x+ft);},'rgba(37,99,235,0.10)',1,1.8);",
      "    drawFn(ccx,ccy,function(x){return Math.cos(x*0.8-ft*0.6)*0.7;},'rgba(124,58,237,0.07)',1,1.4);",
      "    drawFn(ccx,ccy,function(x){return x*x*0.04;},'rgba(220,38,38,0.05)',1,1);",
      "    requestAnimationFrame(draw);",
      "  }",
      "  resize(); draw();",
      "  window.addEventListener('resize', resize);",
      "})();",
    ].join("\n"),

    cursorScript: [
      "(function() {",
      "  document.querySelectorAll('.gp-cursor,.gp-cursor-h-line,.gp-cursor-v-line,.gp-cursor__label').forEach(function(e) { e.remove(); });",
      "  var CELL = 20;",
      "  var dot = document.createElement('div');",
      "  dot.className = 'gp-cursor';",
      "  dot.innerHTML = '<div class=\"gp-cursor__dot\"></div>';",
      "  document.body.appendChild(dot);",
      "  var label = document.createElement('div');",
      "  label.className = 'gp-cursor__label';",
      "  label.style.cssText = 'position:fixed;pointer-events:none;z-index:99999;font-family:IBM Plex Mono,monospace;font-size:9px;color:rgba(37,99,235,0.65);background:rgba(255,255,255,0.88);padding:1px 5px;border-radius:2px;border:1px solid rgba(37,99,235,0.18);white-space:nowrap;';",
      "  document.body.appendChild(label);",
      "  var hLine = document.createElement('div');",
      "  hLine.className = 'gp-cursor-h-line';",
      "  document.body.appendChild(hLine);",
      "  var vLine = document.createElement('div');",
      "  vLine.className = 'gp-cursor-v-line';",
      "  document.body.appendChild(vLine);",
      "  var mx = window.innerWidth/2, my = window.innerHeight/2;",
      "  document.addEventListener('mousemove', function(e) {",
      "    mx = e.clientX; my = e.clientY;",
      "    dot.style.left = mx+'px'; dot.style.top = my+'px';",
      "    hLine.style.top = my+'px'; vLine.style.left = mx+'px';",
      "    var gx = ((mx-window.innerWidth/2)/CELL).toFixed(1);",
      "    var gy = (-(my-window.innerHeight/2)/CELL).toFixed(1);",
      "    label.textContent = '('+gx+', '+gy+')';",
      "    label.style.left = (mx+14)+'px'; label.style.top = (my-20)+'px';",
      "  });",
      "  document.addEventListener('mousedown', function() {",
      "    var d = dot.querySelector('.gp-cursor__dot');",
      "    if (d) d.style.background = 'rgba(37,99,235,0.90)';",
      "  });",
      "  document.addEventListener('mouseup', function() {",
      "    var d = dot.querySelector('.gp-cursor__dot');",
      "    if (d) d.style.background = '';",
      "  });",
      "})();",
    ].join("\n"),

    swatches:      ["#fefefe", "#1d4ed8", "#7c3aed", "#dc2626"],
    previewBg:     "#fefefe",
    previewCard:   "rgba(37,99,235,0.07)",
    previewAccent: "#1d4ed8",
    dark: false,
  },
};

export const THEME_IDS     = Object.keys(THEMES);
export const DEFAULT_THEME = "notebook";
